# Generated by Django 3.2.5 on 2022-03-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-id']},
        ),
    ]
