# Generated by Django 3.2.5 on 2022-03-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField(choices=[(0, '#70bbfb'), (1, '#ff7d7d'), (2, '#f1fc5a'), (3, '#55d634')], null=True)),
                ('icon', models.IntegerField(choices=[(0, 'brutus'), (1, 'bill'), (2, 'genie'), (3, 'grinch'), (4, 'jerry'), (5, 'keiji'), (6, 'kermit'), (7, 'kuroo'), (8, 'lion'), (9, 'melody'), (10, 'mermaid'), (11, 'morty'), (12, 'turtle'), (13, 'cheburashka'), (14, 'amethyst')], null=True)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
