# Generated by Django 3.2.5 on 2022-03-28 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='meeting',
            name='finish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
