# Generated by Django 3.2.5 on 2022-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
