# Generated by Django 3.2.5 on 2022-03-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='grouped_category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
