# Generated by Django 3.2.5 on 2022-01-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='founder',
        ),
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='leader_of', to='clubs.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='theme',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
