# Generated by Django 3.2.5 on 2022-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220127_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='theme',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Hope', 'Hope'), ('Family', 'Family'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Nonfiction'), ('War', 'War'), ('Environment', 'Environment'), ('Identity', 'Identity')], max_length=512),
        ),
    ]
