# Generated by Django 3.2.5 on 2022-02-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_meeting_date'),
        ('clubs', '0002_auto_20220211_1624'),
    ]

    operations = [
    ]
