# Generated by Django 3.2.5 on 2022-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_customavatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customavatar',
            old_name='leader',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customavatar',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='customavatar',
            name='icon',
            field=models.CharField(choices=[('brutus', 'Brutus'), ('bill', 'Bill'), ('genie', 'Genie'), ('grinch', 'Grinch'), ('jerry', 'Jerry'), ('keiji', 'Keiji'), ('kermit', 'Kermit'), ('kuroo', 'Kuroo'), ('lion', 'Lion'), ('melody', 'Melody'), ('mermaid', 'Mermaid'), ('morty', 'Morty'), ('turtle', 'Turtle'), ('cheburashka', 'Cheburashka'), ('amethyst', 'Amethyst')], max_length=28, null=True),
        ),
    ]
