# Generated by Django 3.2.5 on 2022-03-28 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220328_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='finish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='finish'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start'),
        ),
    ]
