# Generated by Django 3.2.5 on 2022-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_booksread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksread',
            name='rating',
            field=models.CharField(choices=[('like', 'like'), ('neutral', 'neutral'), ('dislike', 'dislike')], max_length=30),
        ),
    ]
