# Generated by Django 3.2.5 on 2022-02-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_user_follow_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
