# Generated by Django 3.2.5 on 2022-03-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=205),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
