# Generated by Django 3.2.5 on 2022-01-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220124_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='themes',
        ),
    ]
