# Generated by Django 3.2.5 on 2022-01-26 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_club_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('club', models.CharField(max_length=64, unique=True)),
                ('URL', models.CharField(max_length=520)),
                ('member_selected', models.CharField(max_length=3060)),
                ('next_book', models.CharField(max_length=64, unique=True)),
                ('meeting_notes', models.CharField(max_length=3060)),
            ],
        ),
    ]
