# Generated by Django 3.2.5 on 2022-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='theme',
            field=models.CharField(max_length=512),
        ),
    ]
