# Generated by Django 3.2.5 on 2022-03-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_booksread_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booksread',
            unique_together={('reviewer', 'book')},
        ),
    ]
