# Generated by Django 3.2.5 on 2022-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_notification_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='reciever',
        ),
    ]
