# Generated by Django 3.2.5 on 2022-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20220303_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='using_gravatar',
            field=models.BooleanField(default=False),
        ),
    ]
