# Generated by Django 3.2.5 on 2022-03-28 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20220328_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
