# Generated by Django 3.2.5 on 2022-02-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='acknowledged',
            new_name='acted_upon',
        ),
    ]
