# Generated by Django 3.2.5 on 2022-01-28 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='maximum_members',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(64)]),
        ),
    ]
