# Generated by Django 3.2.5 on 2022-02-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20220205_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chosen_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
