# Generated by Django 3.2.5 on 2022-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_acknowledged_notification_acted_upon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='associated_club',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='associated_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
