# Generated by Django 3.2.5 on 2022-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='associated_club',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='associated_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Became Friends'), (1, 'Club Created'), (2, 'Book Recommendation'), (3, 'Reading New Book'), (4, 'Custom')]),
        ),
    ]
