# Generated by Django 3.2.5 on 2022-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_booksread_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
