# Generated by Django 3.2.5 on 2022-02-10 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20220209_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
