# Generated by Django 3.2.5 on 2022-01-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_reciever_notification_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['isbn']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
