# Generated by Django 3.2.5 on 2022-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_meeting_chosen_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='URL',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
