# Generated by Django 3.2.5 on 2022-01-31 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_reciever_notification_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followes', to=settings.AUTH_USER_MODEL),
        ),
    ]
