# Generated by Django 3.2.5 on 2022-01-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_reciever_notification_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='book',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='members',
        ),
    ]
