# Generated by Django 3.2.5 on 2022-01-30 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20220130_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='book',
            field=models.ManyToManyField(related_name='book', to='clubs.Book'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
