# Generated by Django 3.2.5 on 2022-01-28 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_maximum_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='maximum_members',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(64)]),
        ),
    ]
