# Generated by Django 3.2.5 on 2022-03-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20220324_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='associated_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_club', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='associated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
