# Generated by Django 3.2.5 on 2022-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20220227_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='URL',
            field=models.CharField(blank=True, default='qaz', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
